export type DocumentWhere =
  | `Block ${number}`
  | `Layer2 meetup ${number} @${string}`
  | "Other";
export type DocumentAuthor = "IKP" | "FASE" | "CS" | "IGWP" | "KSG" | "Other";
export type DocumentLanguage = "JP" | "EN";
export type DocumentWhat =
  | "meeting_report"
  | "study_report"
  | "news_letter"
  | "governance_doc"
  | "working_doc"
  | "other";

export interface Document {
  id: string;
  title: string;
  path: string; // relative to public/documents/
  where: DocumentWhere;
  when: string; // "YYYY/MM" or "unclear"
  author: DocumentAuthor;
  language: DocumentLanguage;
  what: DocumentWhat;
}

export const documents: Document[] = [
  // ===== Block 1 (June 2020 BGIN founding) =====
  // when: confirmed by governance/20200611_ filenames (Jun 11, 2020)
  {
    id: "B01_mr_01",
    title: "Block 1 Meeting Report",
    path: "meeting-reports/block1/Block1MeetingrReport.pdf",
    where: "Block 1",
    when: "2020/11",
    author: "Other",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "-",
    title: "Discussion Materials: BGIN Org Roadmap",
    path: "block-events/block1/Discussion_Materials_BGIN_Org_Roadmap.pdf",
    where: "Block 1",
    when: "2020/06",
    author: "Other",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Closing Plenary Slides",
    path: "block-events/block1/Closing_Plenary_Slides.pdf",
    where: "Block 1",
    when: "2020/06",
    author: "Other",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "Day 1 Opening Plenary Slides",
    path: "block-events/block1/Day1_Opening_Plenary_Slides.pdf",
    where: "Block 1",
    when: "2020/06",
    author: "Other",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "Tutorial Session 1 Slides",
    path: "block-events/block1/Tutorial_Session1_Slides.pdf",
    where: "Block 1",
    when: "2020/11",
    author: "Other",
    language: "EN",
    what: "other",
  },

  // ===== Block 2 =====
  // when: 2021/03 ? confirmed from Welcome_Introductions_Slides.pdf "March 8, 2021"
  {
    id: "-",
    title: "Frederic de Vaulx - Prometheus Slides",
    path: "block-events/block2/Frederic_de_Vaulx_Prometheus_Slides.pdf",
    where: "Block 2",
    when: "2021/03",
    author: "Other",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "Jack Gavigan - Zcash Slides",
    path: "block-events/block2/Jack_Gavigan_Zcash_Slides.pdf",
    where: "Block 2",
    when: "2021/03",
    author: "Other",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "James Angel - Georgetown Slides",
    path: "block-events/block2/James_Angel_Georgetown_Slides.pdf",
    where: "Block 2",
    when: "2021/03",
    author: "Other",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "Welcome & Introductions Slides",
    path: "block-events/block2/Welcome_Introductions_Slides.pdf",
    where: "Block 2",
    when: "2021/03",
    author: "Other",
    language: "EN",
    what: "other",
  },

  // ===== Block 4 =====
  // when: 2021/11 ? confirmed from Block4_Meeting_Report_GDocs.pdf "November 2-4, 2021"
  {
    // Block 4 MR stored in block12 folder; where reflects document's subject
    id: "B04_mr_01",
    title: "Block 4 Meeting Report",
    path: "block-events/block12/Block4_Meeting_Report_GDocs.pdf",
    where: "Block 4",
    when: "2021/11",
    author: "Other",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B04_mr_02",
    title: "Block 4 Meeting Report",
    path: "meeting-reports/block4/Block4MeetingrReport.pdf",
    where: "Block 4",
    when: "2021/11",
    author: "Other",
    language: "EN",
    what: "meeting_report",
  },

  // ===== Block 8 =====
  // when: 2023/05 ? confirmed from Block8MeetingrReport.pdf "May 4-7, 2023"
  {
    id: "B08_mr_01",
    title: "Block 8 Meeting Report",
    path: "meeting-reports/block8/Block8MeetingrReport.pdf",
    where: "Block 8",
    when: "2023/05",
    author: "Other",
    language: "EN",
    what: "meeting_report",
  },

  // ===== Block 9 =====
  // when: 2023/11 ? confirmed from PDFs (sessions dated Nov 20-21, 2023)
  {
    id: "B09_mr_01",
    title: "Block 9 MR: Accountable Wallet",
    path: "meeting-reports/block9/BGIN Block #9 Accountable Wallet MR.pdf",
    where: "Block 9",
    when: "2023/11",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B09_mr_02",
    title: "Block 9 MR: CBDC and Privacy",
    path: "meeting-reports/block9/BGIN Block #9 CBDC and Privacy MR.pdf",
    where: "Block 9",
    when: "2023/11",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B09_mr_03",
    title: "Block 9 MR: Digital Identity",
    path: "meeting-reports/block9/BGIN Block #9 Digital Identity MR.pdf",
    where: "Block 9",
    when: "2023/11",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B09_mr_04",
    title: "Block 9 MR: Potential Failure of Stablecoin",
    path: "meeting-reports/block9/BGIN Block #9 Potential Failure of Stablecoin MR.pdf",
    where: "Block 9",
    when: "2023/11",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B09_mr_05",
    title: "Block 9 MR: Smart Contract Security, Governance, and Impact of AI",
    path: "meeting-reports/block9/BGIN Block #9 Smart Contract Security, Governance, and Impact of AI MR.pdf",
    where: "Block 9",
    when: "2023/11",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B09_mr_06",
    title: "Block 9 MR: Transparency of dApps and Sound DeFi",
    path: "meeting-reports/block9/BGIN Block #9 Transparency of dApps and Sound DeFi.pdf",
    where: "Block 9",
    when: "2023/11",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B09_mr_07",
    title: "Block 9 MR: Worldcoin",
    path: "meeting-reports/block9/BGIN Block #9 Worldcoin MR.pdf",
    where: "Block 9",
    when: "2023/11",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B09_mr_08",
    title: "Block 9 MR: ZKP and its Application",
    path: "meeting-reports/block9/BGIN Block #9 ZKP and its Application MR.pdf",
    where: "Block 9",
    when: "2023/11",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },

  // ===== Block 10 (March 3-5, 2024) =====
  // when: confirmed from folder names "Day 1 (Sunday, March 3rd 2024)"
  {
    id: "B10_mr_01",
    title: "Block 10 MR: Financial Stability Challenges",
    path: "meeting-reports/block10/Day 1 (Sunday, March 3rd 2024)/BGIN Block #10 Meeting Report_Financial Stability Challenges.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_02",
    title: "Block 10 MR: Internet Governance",
    path: "meeting-reports/block10/Day 1 (Sunday, March 3rd 2024)/BGIN Block #10 Meeting Report_Internet Governance.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "IGWP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_03",
    title: "Block 10 MR: Privacy vs Discoverability",
    path: "meeting-reports/block10/Day 1 (Sunday, March 3rd 2024)/BGIN Block #10 Meeting Report_Privacy vs Discoverability.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_04",
    title: "Block 10 MR: Challenges and Innovations in On-Chain Analysis",
    path: "meeting-reports/block10/Day 2 (Monday, March 4th 2024)/BGIN Block #10 Meeting Report_Challenges and Innovations in On-Chain Analysis.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_05",
    title: "Block 10 MR: Harmonization of CBDC, Deposit Tokens, Stablecoins, and DeFi",
    path: "meeting-reports/block10/Day 2 (Monday, March 4th 2024)/BGIN Block #10 Meeting Report_Harmonization of CBDC, Deposit Tokens, Stablecoins, and DeFi.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_06",
    title: "Block 10 MR: Illicit Activity",
    path: "meeting-reports/block10/Day 2 (Monday, March 4th 2024)/BGIN Block #10 Meeting Report_Illicit Activity.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_07",
    title: "Block 10 MR: Smart Contract Security",
    path: "meeting-reports/block10/Day 2 (Monday, March 4th 2024)/BGIN Block #10 Meeting Report_Smart Contract Security.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_08",
    title: "Block 10 MR: The Mutual Impact and Improved Outcomes of Blockchain & AI",
    path: "meeting-reports/block10/Day 2 (Monday, March 4th 2024)/BGIN Block #10 Meeting Report_The Mutual Impact and Improved Outcomes of Blockchain & AI.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_09",
    title: "Block 10 MR: The Role of DAO in the Modern World",
    path: "meeting-reports/block10/Day 2 (Monday, March 4th 2024)/BGIN Block #10 Meeting Report_The Role of DAO in the Modern World.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "IGWP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_10",
    title: "Block 10 MR: Tokenization and Real-World Assets",
    path: "meeting-reports/block10/Day 2 (Monday, March 4th 2024)/BGIN Block #10 Meeting Report_Tokenization and Real-World Assets.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_11",
    title: "Block 10 MR: Transparency of dApps and Sound DeFi",
    path: "meeting-reports/block10/Day 2 (Monday, March 4th 2024)/BGIN Block #10 Meeting Report_Transparency of dApps and Sound DeFi.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_12",
    title: "Block 10 MR: Day 3 Wrap",
    path: "meeting-reports/block10/Day 3 (Tuesday, March 5th 2024)/BGIN Block #10 Meeting Report_Day3 Wrap.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "Other",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_13",
    title: "Block 10 MR: Incident Response",
    path: "meeting-reports/block10/Day 3 (Tuesday, March 5th 2024)/BGIN Block #10 Meeting Report_Incident Response.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_14",
    title: "Block 10 MR: Layer2 Governance - KeyNote",
    path: "meeting-reports/block10/Day 3 (Tuesday, March 5th 2024)/BGIN Block #10 Meeting Report_Layer2 Governance_KeyNote.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "IGWP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_15",
    title: "Block 10 MR: Layer2 Governance - Roundtable",
    path: "meeting-reports/block10/Day 3 (Tuesday, March 5th 2024)/BGIN Block #10 Meeting Report_Layer2 Governance_Roundtable.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "IGWP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_16",
    title: "Block 10 MR: Privacy Pool & Accountable Wallet",
    path: "meeting-reports/block10/Day 3 (Tuesday, March 5th 2024)/BGIN Block #10 Meeting Report_Privacy pool _ Accountable Wallet.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_17",
    title: "Block 10 MR: SBT Paper Part 2",
    path: "meeting-reports/block10/Day 3 (Tuesday, March 5th 2024)/BGIN Block #10 Meeting Report_SBT Paper Part 2.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_18",
    title: "Block 10 MR: TEMP",
    path: "meeting-reports/block10/Day 3 (Tuesday, March 5th 2024)/BGIN Block #10 Meeting Report_TEMP.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "Other",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_19",
    title: "Block 10 MR: Wallet Governance and Credential Management",
    path: "meeting-reports/block10/Day 3 (Tuesday, March 5th 2024)/BGIN Block #10 Meeting Report_Wallet Governance and Credential Management.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B10_mr_20",
    title: "Block 10 MR: ZKP and its Application",
    path: "meeting-reports/block10/Day 3 (Tuesday, March 5th 2024)/BGIN Block #10 Meeting Report_ZKP and its Application.pdf",
    where: "Block 10",
    when: "2024/03",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },

  // ===== Block 11 (October 2024) =====
  // when: confirmed by projects/ai-blockchain/241013 prefix (Oct 13, 2024)
  {
    id: "B11_mr_01",
    title: "Block 11 MR: AI and Blockchain Governance",
    path: "meeting-reports/block11/BGIN Block#11 MR AI and Blockchain Governance.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B11_mr_02",
    title: "Block 11 MR: CryptoISACs with BGIN",
    path: "meeting-reports/block11/BGIN Block#11 MR CryptoISACs with BGIN.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B11_mr_03",
    title: "Block 11 MR: Cybersecurity Information Sharing Alignment",
    path: "meeting-reports/block11/BGIN Block#11 MR Cybersecurity Information Sharing Alignment.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B11_mr_04",
    title: "Block 11 MR: FTX Collapse and Capital Risk Framework",
    path: "meeting-reports/block11/BGIN Block#11 MR FTX Collapse and Capital Risk Framework.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B11_mr_05",
    title: "Block 11 MR: Innovation and Challenges of Blockchain Analysis",
    path: "meeting-reports/block11/BGIN Block#11 MR Innovation and Challenges of Blockchain Analysis.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B11_mr_06",
    title: "Block 11 MR: Institutional Adoption and Regulatory Frontier for Emerging Technologies",
    path: "meeting-reports/block11/BGIN Block#11 MR Institutional Adoption and Regulatory Frontier for Emerging Technologies.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "IGWP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B11_mr_07",
    title: "Block 11 MR: L2 Governance",
    path: "meeting-reports/block11/BGIN Block#11 MR L2 Governance.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "IGWP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B11_mr_08",
    title: "Block 11 MR: Tokenization Initiatives",
    path: "meeting-reports/block11/BGIN Block#11 MR Tokenization Initiatives.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B11_mr_09",
    title: "Block 11 MR: Wallet Governance",
    path: "meeting-reports/block11/BGIN Block#11 MR Wallet Governance.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    // duplicate of meeting-reports/block11/
    id: "B11_mr_10",
    title: "Block 11 MR: CryptoISACs with BGIN (CS archive copy)",
    path: "projects/cybersecurity-standards/BGIN Block#11 MR CryptoISACs with BGIN.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    // duplicate of meeting-reports/block11/
    id: "B11_mr_11",
    title: "Block 11 MR: Cybersecurity Information Sharing Alignment (CS archive copy)",
    path: "projects/cybersecurity-standards/BGIN Block#11 MR Cybersecurity Information Sharing Alignment.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    // duplicate of meeting-reports/block11/
    id: "B11_mr_12",
    title: "Block 11 MR: L2 Governance (Study Report archive copy)",
    path: "study-reports/layer2-governance/BGIN Block#11 MR L2 Governance.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "IGWP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "-",
    title: "BGIN Block 11: AI & Blockchain Governance (Working Doc)",
    path: "projects/ai-blockchain/241013 BGIN _ Block#11 AI & Blockchain Governance.pdf",
    where: "Block 11",
    when: "2024/10", // 241013 = Oct 13, 2024
    author: "FASE",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Layer2 Governance - Block 11 Working Doc",
    path: "study-reports/layer2-governance/241023_Layer2 Governance_Block11.pdf",
    where: "Block 11",
    when: "2024/10", // 241023 = Oct 23, 2024
    author: "IGWP",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Block 11 Agenda (Tentative)",
    path: "block-events/block11/Block11_Agenda_Tentative.pdf",
    where: "Block 11",
    when: "2024/10",
    author: "Other",
    language: "EN",
    what: "other",
  },

  // ===== Block 12 (March 2-3, 2025, Tokyo) =====
  // when: 2025/03 ? confirmed from Block12_Agenda_Tentative.pdf "Day 1 (March 2nd, Sunday)"
  {
    id: "B12_mr_01",
    title: "BGIN Block 12 Meeting Report",
    path: "block13/session-docs/BGIN_Block12_Meeting_Report.pdf",
    where: "Block 12",
    when: "2025/03", // Block 12 confirmed: March 2-3, 2025 (Tokyo)
    author: "Other",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_02",
    title: "Block 12 MR: Block 12 Tokyo, JAPAN (Overview)",
    path: "meeting-reports/block12/BGIN Block#12 MR  Block#12 Tokyo, JAPAN.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "Other",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_03",
    title: "Block 12 MR: Cybersecurity Education",
    path: "meeting-reports/block12/BGIN Block#12 MR  Cybersecurity Education.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_04",
    title: "Block 12 MR: Cybersecurity Information Sharing Framework",
    path: "meeting-reports/block12/BGIN Block#12 MR  Cybersecurity Information Sharing Framework.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_05",
    title: "Block 12 MR: Development of ST/PP",
    path: "meeting-reports/block12/BGIN Block#12 MR  Development of ST_PP.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_06",
    title: "Block 12 MR: Financial Stability Risk within Decentralized Financial System",
    path: "meeting-reports/block12/BGIN Block#12 MR  Financial Stability Risk within Decentralized Financial System.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_07",
    title: "Block 12 MR: Layer2 Governance",
    path: "meeting-reports/block12/BGIN Block#12 MR  Layer2 Governance.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "IGWP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_08",
    title: "Block 12 MR: Stablecoin Challenges",
    path: "meeting-reports/block12/BGIN Block#12 MR  Stablecoin Challenges.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_09",
    title: "Block 12 MR: Blockchain Analysis and Forensic Analysis",
    path: "meeting-reports/block12/BGIN Block#12 MR Blockchain Analysis and Forensic Analysis.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_10",
    title: "Block 12 MR: The Mutual Impact and Improved Outcome of AI & Blockchain",
    path: "meeting-reports/block12/BGIN Block#12 MR The Mutual Impact and Improved Outcome of AI & Blockchain.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_11",
    title: "Block 12 MR: Tokenization Initiatives",
    path: "meeting-reports/block12/BGIN Block#12 MR Tokenization Iniatives.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_12",
    title: "Block 12 MR: Transition to Post-Quantum Cryptography & Crypto Agility",
    path: "meeting-reports/block12/BGIN Block#12 MR Transition to Post-Quantum Cryptography _  Crypto Agility.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B12_mr_13",
    title: "Block 12 MR: Wallet Governance & Accountable Wallet",
    path: "meeting-reports/block12/BGIN Block#12 MR Wallet Governance _ Accountable Wallet.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "-",
    title: "Block 12 Agenda (Tentative)",
    path: "block-events/block12/Block12_Agenda_Tentative.pdf",
    where: "Block 12",
    when: "2025/03",
    author: "Other",
    language: "EN",
    what: "other",
  },

  // ===== Block 13 (October 15-17, 2025) =====
  // when: confirmed from events page (block13 = Oct 15-17, 2025)
  {
    id: "B13_mr_01",
    title: "Offline Key Management",
    path: "block13/1-1 Offline Key Management.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B13_mr_02",
    title: "Governance of Security Supply Chain",
    path: "block13/1-2 Governance of Security Supply Chain.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B13_mr_03",
    title: "Information Sharing Framework Standard",
    path: "block13/1-3 Information Sharing Framework Standard.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B13_mr_04",
    title: "ZKP and Privacy Enhanced Authentication",
    path: "block13/1-4 ZKP and Privacy Enhanced Authentication.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B13_mr_05",
    title: "Security Target and Protection Profile",
    path: "block13/2-1 Security Target and Protection Profile.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B13_mr_06",
    title: "Crypto Agility and PQC Migration",
    path: "block13/2-2 Crypto Agility and PQC Migration.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B13_mr_07",
    title: "Accountable Wallets",
    path: "block13/3-1-1 Accountable Wallets.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B13_mr_08",
    title: "Establishing Technical Metrics to Evaluate the Decentralization of Blockchain Networks",
    path: "block13/3-1-2 Establishing Technical Metrics to Evaluate the Decentralization of Blockchain Networks.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "Other",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B13_mr_09",
    title: "Forensics and Analysis Toward a Common Lexicon for Harmful On-Chain Activities",
    path: "block13/3-2 Forensics and Analysis Toward a Common Lexicon for Harmful On-Chain Activities.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B13_mr_10",
    title: "BGIN Agent Hack Final Presentation",
    path: "block13/3-3 BGIN Agent Hack Final Presentation.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "Other",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B13_mr_11",
    title: "Practical Stablecoin Implementation Guide",
    path: "block13/3-4 Practical Stablecoin Implementation Guide.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "B13_mr_12",
    title: "Harmonization among Crypto-asset, Stablecoin and Tokenized Deposit",
    path: "block13/3-5 Harmonization among Crypto-asset, stablecoin and tokenized deposit .pdf",
    where: "Block 13",
    when: "2025/10",
    author: "FASE",
    language: "EN",
    what: "meeting_report",
  },
  // Block 13 session-docs (working_doc)
  {
    id: "-",
    title: "Beyond Static Governance: AI Agent",
    path: "block13/session-docs/Beyond_Static_Governance_AI_Agent.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "FASE",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Cyber Security Info Sharing Framework ISO Draft",
    path: "block13/session-docs/Cyber_Security_Info_Sharing_Framework_ISO_Draft.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "CS",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Discussion Points: Blockchain Decentralization",
    path: "block13/session-docs/Discussion_Points_Blockchain_Decentralization.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "Other",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Discussion Points: Harmful Activities",
    path: "block13/session-docs/Discussion_Points_Harmful_Activities.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "IKP",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Distinguishing Blockchain Forensics from Analytics",
    path: "block13/session-docs/Distinguishing_Blockchain_Forensics_Analytics.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "IKP",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Policy Priorities for Stablecoin Regulation",
    path: "block13/session-docs/Policy_Priorities_Stablecoin_Regulation.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "FASE",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Post-Quantum Blockchain Transition",
    path: "block13/session-docs/Post_Quantum_Blockchain_Transition.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "CS",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "ZKP and its Application",
    path: "block13/session-docs/ZKP_and_its_Application.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "IKP",
    language: "EN",
    what: "working_doc",
  },
  // Block 13 other
  {
    id: "-",
    title: "BGIN Block 13 Program - Tentative",
    path: "block13/BGIN Block 13 Program - Tentative Program.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "Other",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "JPCrypto-ISAC Presentation (Oct 15, 2025)",
    path: "block13/JPCrypto-ISAC_10152025Presentation.pdf",
    where: "Block 13",
    when: "2025/10", // 10152025 = Oct 15, 2025
    author: "CS",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "Stake Holder Chart",
    path: "block13/session-docs/Stake_Holder_Chart.pdf",
    where: "Block 13",
    when: "2025/10",
    author: "Other",
    language: "EN",
    what: "other",
  },

  // ===== Block 14 (March 1-2, 2026) =====
  // when: confirmed from events page
  {
    id: "-",
    title: "Blockchain Business Structure",
    path: "block14/blockchain-business-structure_02252026.pdf",
    where: "Block 14",
    when: "2026/02", // 02252026 = Feb 25, 2026 in filename
    author: "Other",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "JVCEA Changes Packet",
    path: "block14/jvcea_changes_packet.pdf",
    where: "Block 14",
    when: "2026/03", // no date in filename; placed in block14 folder (Mar 1-2, 2026)
    author: "Other",
    language: "EN",
    what: "other",
  },

  // ===== Layer2 Meetup 2024 @Tokyo (September 2024) =====
  // when: 2024/09 - confirmed by study-reports/layer2-governance/240920_ prefix
  {
    id: "L2_24TYO_mr_01",
    title: "Layer2 Meetup @Tokyo MR: Cybersecurity Information-Sharing",
    path: "meeting-reports/layer2-tokyo/BGIN Layer2Meetup@Tokyo Meeting Report_Cybersecurity Information-Sharing.pdf",
    where: "Layer2 meetup 2024 @Tokyo",
    when: "2024/09",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "L2_24TYO_mr_02",
    title: "Layer2 Meetup @Tokyo MR: Regulatory Uncertainty for Lightning Business",
    path: "meeting-reports/layer2-tokyo/BGIN Layer2Meetup@Tokyo Meeting Report_Regulatory Uncertainty for Lightning Business.pdf",
    where: "Layer2 meetup 2024 @Tokyo",
    when: "2024/09",
    author: "IGWP",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "L2_24TYO_mr_03",
    title: "Layer2 Meetup @Tokyo MR: Wallet Governance",
    path: "meeting-reports/layer2-tokyo/BGIN Layer2Meetup@Tokyo Meeting Report_Wallet Governance.pdf",
    where: "Layer2 meetup 2024 @Tokyo",
    when: "2024/09",
    author: "IKP",
    language: "EN",
    what: "meeting_report",
  },
  {
    // duplicate of meeting-reports/layer2-tokyo/
    id: "L2_24TYO_mr_04",
    title: "Layer2 Meetup @Tokyo MR: Cybersecurity Information-Sharing (CS archive copy)",
    path: "projects/cybersecurity-standards/BGIN Layer2Meetup@Tokyo Meeting Report_Cybersecurity Information-Sharing.pdf",
    where: "Layer2 meetup 2024 @Tokyo",
    when: "2024/09",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "L2_24TYO_mr_05",
    title: "Layer2 Meetup @Tokyo MR: Regulatory Uncertainty for Lightning Businesses (Study Report archive)",
    path: "study-reports/layer2-governance/240920_BGIN Layer2Meetup@Tokyo Meeting Report_Regulatory Uncertainty for Lightning Businesses.pdf",
    where: "Layer2 meetup 2024 @Tokyo",
    when: "2024/09", // 240920 = Sep 20, 2024
    author: "IGWP",
    language: "EN",
    what: "meeting_report",
  },

  // ===== Layer2 Meetup 2024 @Sydney =====
  // when: 2024/10 ? confirmed from PDF "October 2th, 2024"
  {
    id: "L2_24SYD_mr_01",
    title: "Layer2 Meetup @Sydney MR: Cybersecurity Information-Sharing",
    path: "meeting-reports/layer2-sydney/BGIN Layer2Meetup@Sydney Meeting Report_Cybersecurity Information-Sharing.pdf",
    where: "Layer2 meetup 2024 @Sydney",
    when: "2024/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    // duplicate of meeting-reports/layer2-sydney/
    id: "L2_24SYD_mr_02",
    title: "Layer2 Meetup @Sydney MR: Cybersecurity Information-Sharing (CS archive copy)",
    path: "projects/cybersecurity-standards/BGIN Layer2Meetup@Sydney Meeting Report_Cybersecurity Information-Sharing.pdf",
    where: "Layer2 meetup 2024 @Sydney",
    when: "2024/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },

  // ===== Layer2 Meetup 2024 @SF (October 2024) =====
  // when: 2024/10 - confirmed by study-reports/layer2-governance/241020_ prefix
  {
    id: "L2_24SFO_mr_01",
    title: "Layer2 Meetup @SF MR: Cybersecurity Information-Sharing",
    path: "meeting-reports/layer2-sf/BGIN Layer2Meetup@SF Meeting Report_Cybersecurity Information-Sharing.pdf",
    where: "Layer2 meetup 2024 @SF",
    when: "2024/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    // duplicate of meeting-reports/layer2-sf/
    id: "L2_24SFO_mr_02",
    title: "Layer2 Meetup @SF MR: Cybersecurity Information-Sharing (CS archive copy)",
    path: "projects/cybersecurity-standards/BGIN Layer2Meetup@SF Meeting Report_Cybersecurity Information-Sharing.pdf",
    where: "Layer2 meetup 2024 @SF",
    when: "2024/10",
    author: "CS",
    language: "EN",
    what: "meeting_report",
  },
  {
    id: "-",
    title: "Layer2 Meetup @SF - Transcript",
    path: "meeting-reports/layer2-sf/Layer2_SF_Transcript.pdf",
    where: "Layer2 meetup 2024 @SF",
    when: "2024/10",
    author: "Other",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "Layer2 Meetup @SF - Slides (Oct 2024)",
    path: "study-reports/layer2-governance/241020_Layer2 Meetup at San Francisco.pdf",
    where: "Layer2 meetup 2024 @SF",
    when: "2024/10", // 241020 = Oct 20, 2024
    author: "Other",
    language: "EN",
    what: "other",
  },

  // ===== Layer2 Meetup 2025 @Tokyo (ETH Tokyo / EDCON, April 2025) =====
  // when: 2025/09 ? confirmed from PDF "September 15, 2025 (ETHTokyo)"
  {
    id: "-",
    title: "BGIN Layer2 Meetup ETH Tokyo / EDCON News Release (JP)",
    path: "events/layer2-japan-2025/BGIN_Layer2_Meetup_ETHTOKYO_EDCON_NEWS_Release_J.pdf",
    where: "Layer2 meetup 2025 @Tokyo",
    when: "2025/09",
    author: "Other",
    language: "JP",
    what: "other",
  },
  {
    id: "-",
    title: "Layer2 Meet Up @ETH Tokyo - Agenda",
    path: "events/layer2-japan-2025/Layer2 Meet Up@Eth Tokyo.pdf",
    where: "Layer2 meetup 2025 @Tokyo",
    when: "2025/09",
    author: "Other",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "BGIN Layer2 Meetup ETH Tokyo / EDCON News Release (EN)",
    path: "events/layer2-japan-2025/Layer2Meetup_ETHTOYKO_EDCON_NEWS_Release_E.pdf",
    where: "Layer2 meetup 2025 @Tokyo",
    when: "2025/09",
    author: "Other",
    language: "EN",
    what: "other",
  },

  // ===== Other =====
  // ---- Meeting Reports ----
  {
    id: "-",
    title: "2020 Online Meeting Report",
    path: "study-reports/online-meeting-2020/20200618OnlineMeetingReport.pdf",
    where: "Other",
    when: "2020/06", // 20200618 in filename
    author: "Other",
    language: "EN",
    what: "meeting_report",
  },

  // ---- Working Docs ----
  {
    id: "-",
    title: "Draft: BGIN Accountable Wallet",
    path: "projects/accountable-wallet/Draft_BGIN - Accountable Wallet.pdf",
    where: "Other",
    when: "unclear",
    author: "IKP",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Draft: BGIN Accountable Wallet (Copy)",
    path: "projects/accountable-wallet/Copy of Draft_BGIN - Accountable Wallet.pdf",
    where: "Other",
    when: "unclear",
    author: "IKP",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Learning from Bitcoin Fog Case",
    path: "projects/blockchain-analysis/250126_Learning from Bitcoin Fog Case.pdf",
    where: "Other",
    when: "2025/01", // 250126 = Jan 26, 2025
    author: "IKP",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Distinguishing Blockchain Forensics from Analytics",
    path: "projects/blockchain-analysis/BGIN IKP Working Group Distinguishing Blockchain Forensics from Analytics.pdf",
    where: "Other",
    when: "unclear",
    author: "IKP",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Blockchain Forensics vs Analytics Research - Interview Doc",
    path: "projects/blockchain-analysis/Blockchain Forensics vs Analytics Research - interview doc.pdf",
    where: "Other",
    when: "unclear",
    author: "IKP",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Distinguishing Blockchain Forensics from Analytics (Jan 30, 2025 Working Docs)",
    path: "projects/blockchain-analysis/Distinguishing Blockchain Forensics from Analytics2025jan30_working docs.pdf",
    where: "Other",
    when: "2025/01", // "2025jan30" in filename
    author: "IKP",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "CS-WG Meeting Agenda #1",
    path: "projects/cybersecurity-standards/250130 CS-WG Meeting Agenda #1.pdf",
    where: "Other",
    when: "2025/01", // 250130 = Jan 30, 2025
    author: "CS",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "CS-WG Meeting Note #1",
    path: "projects/cybersecurity-standards/250130 CS-WG Meeting Note #1.pdf",
    where: "Other",
    when: "2025/01", // 250130 = Jan 30, 2025
    author: "CS",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "CS-WG Meeting Agenda #2",
    path: "projects/cybersecurity-standards/250214 CS-WG Meeting Agenda #2.pdf",
    where: "Other",
    when: "2025/02", // 250214 = Feb 14, 2025
    author: "CS",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "CS-WG Meeting Note #2",
    path: "projects/cybersecurity-standards/250218 CS-WG Meeting Note #2.pdf",
    where: "Other",
    when: "2025/02", // 250218 = Feb 18, 2025
    author: "CS",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "CS-WG Meeting Agenda #3-1&2",
    path: "projects/cybersecurity-standards/250224 CS-WG Meeting Agenda #3-1&2.pdf",
    where: "Other",
    when: "2025/02", // 250224 = Feb 24, 2025
    author: "CS",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "BGIN Information Sharing Framework (Aug 2025)",
    path: "projects/cybersecurity-standards/BGIN_InformationSharingFW_08112025.pdf",
    where: "Other",
    when: "2025/08", // 08112025 = Aug 11, 2025
    author: "CS",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "BGIN Cybersecurity Roadmap",
    path: "projects/cybersecurity-standards/BGIN_Roadmap_Cybersecurity.pdf",
    where: "Other",
    when: "unclear",
    author: "CS",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Cyber Security Information Sharing Framework (May 2025)",
    path: "projects/cybersecurity-standards/Cyber Security Information Sharing Framework_250515.pdf",
    where: "Other",
    when: "2025/05", // 250515 = May 15, 2025
    author: "CS",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Cybersecurity Information Sharing Alignment for Crypto",
    path: "projects/cybersecurity-standards/Cybersecurity Information Sharing Alignment for Crypto.pdf",
    where: "Other",
    when: "unclear",
    author: "CS",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Stablecoin Regulation Comparison v1",
    path: "projects/stablecoin-research/Stablecoin regulation comparison v1.pdf",
    where: "Other",
    when: "unclear",
    author: "FASE",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "Stablecoin Regulation Comparison v2",
    path: "projects/stablecoin-research/Stablecoin regulation comparison v2.pdf",
    where: "Other",
    when: "unclear",
    author: "FASE",
    language: "EN",
    what: "working_doc",
  },
  {
    id: "-",
    title: "BGIN Working Document: Layer2 Governance Study Report",
    path: "study-reports/layer2-governance/BGIN_WD_SR00___ Layer2 Governance.pdf",
    where: "Other",
    when: "unclear",
    author: "IGWP",
    language: "EN",
    what: "working_doc",
  },

  // ---- Other (study reports, newsletters, external, etc.) ----
  {
    id: "-",
    title: "FSA Research Paper on BGIN (Part 1)",
    path: "external/FSA_Research_Paper_BGIN_en1.pdf",
    where: "Other",
    when: "2022/06",
    author: "Other",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "FSA Research Paper on BGIN (Part 2)",
    path: "external/FSA_Research_Paper_BGIN_en2.pdf",
    where: "Other",
    when: "2023/06",
    author: "Other",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "BGIN May 2025 WG Newsletter",
    path: "newsletters/BGIN May 2025 WG Newsletter.pdf",
    where: "Other",
    when: "2025/05",
    author: "Other",
    language: "EN",
    what: "news_letter",
  },
  {
    id: "-",
    title: "BGIN June 2025 WG Newsletter",
    path: "newsletters/BGIN June 2025 WG Newsletter.pdf",
    where: "Other",
    when: "2025/06",
    author: "Other",
    language: "EN",
    what: "news_letter",
  },
  {
    id: "-",
    title: "BGIN July 2025 Newsletter",
    path: "newsletters/BGIN July 2025 Newsletter.pdf",
    where: "Other",
    when: "2025/07",
    author: "Other",
    language: "EN",
    what: "news_letter",
  },
  {
    id: "-",
    title: "BGIN August 2025 Newsletter",
    path: "newsletters/BGIN August 2025 Newsletter.pdf",
    where: "Other",
    when: "2025/08",
    author: "Other",
    language: "EN",
    what: "news_letter",
  },
  {
    id: "-",
    title: "Link to WG Co-Working Sheet",
    path: "projects/cybersecurity-standards/Link to the WG co-working sheet.pdf",
    where: "Other",
    when: "unclear",
    author: "CS",
    language: "EN",
    what: "other",
  },
  {
    id: "-",
    title: "VerifyVASP",
    path: "sponsors/VerifyVasp.pdf",
    where: "Other",
    when: "unclear",
    author: "Other",
    language: "EN",
    what: "other",
  },
  {
    id: "sr_001",
    title: "Study Report: Present and Future of a Decentralized Financial System (DeFi)",
    path: "study-reports/defi/20210101_Defi.pdf",
    where: "Other",
    when: "2021/01", // 20210101 in filename
    author: "Other",
    language: "EN",
    what: "study_report",
  },
  {
    id: "sr_003",
    title: "Study Report: Incident Response of Decentralized Custody",
    path: "study-reports/custody/20220606_Custody.pdf",
    where: "Other",
    when: "2022/06", // 20220606 in filename
    author: "Other",
    language: "EN",
    what: "study_report",
  },
  {
    id: "sr_005",
    title: "Study Report: NFT Part 1 - Introduction and Use Cases",
    path: "study-reports/nft/20220606_NFT.pdf",
    where: "Other",
    when: "2022/06", // 20220606 in filename
    author: "Other",
    language: "EN",
    what: "study_report",
  },
  {
    id: "sr_006",
    title: "Study Report: Ransomware Reaction",
    path: "study-reports/ransomware/20220421_Ransomware.pdf",
    where: "Other",
    when: "2022/04", // 20220421 in filename
    author: "Other",
    language: "EN",
    what: "study_report",
  },
  {
    id: "sr_007",
    title: "Study Report: Selective Disclosure - Overview and Classifications",
    path: "study-reports/selective-disclosure/20230428_Selective_Disclosure.pdf",
    where: "Other",
    when: "2023/04", // 20230428 in filename
    author: "IKP",
    language: "EN",
    what: "study_report",
  },
  {
    id: "sr_008",
    title: "Study Report: Soulbound Tokens (SBTs) Part 1",
    path: "study-reports/sbt-part1/20230201_SBT.pdf",
    where: "Other",
    when: "2023/02", // 20230201 in filename
    author: "IKP",
    language: "EN",
    what: "study_report",
  },
  {
    id: "sr_010",
    title: "Study Report: Proposal of Principles of DeFi Disclosure and Regulation",
    path: "study-reports/defi-disclosure/20230213_Defi_Disclosure.pdf",
    where: "Other",
    when: "2023/02", // 20230213 in filename
    author: "FASE",
    language: "EN",
    what: "study_report",
  },
  {
    id: "sr_010",
    title: "Wallet Governance and Key Management Study Report",
    path: "study-reports/Wallet_Governance_Key_Management_Study_Report.pdf",
    where: "Other",
    when: "unclear",
    author: "IKP",
    language: "EN",
    what: "study_report",
  },
  {
    id: "sr_",
    title: "Study Report: Present and Future of Stablecoin and DeFi",
    path: "study-reports/stablecoins-defi/20230329_Stablecoin_and_Defi.pdf",
    where: "Other",
    when: "2023/03", // 20230329 in filename
    author: "FASE",
    language: "EN",
    what: "study_report",
  },
  {
    id: "sr_011",
    title: "Study Report: Potential Points of Failure of Stablecoins and DeFi",
    path: "study-reports/stablecoins-defi/20230724_PoF_of_Stablecoins.pdf",
    where: "Other",
    when: "2023/07", // 20230724 in filename
    author: "FASE",
    language: "EN",
    what: "study_report",
  },
  {
    id: "sr_011",
    title: "ZKP Study Report (BGIN SR 0011) v2",
    path: "study-reports/zkp/BGIN SR 0011_zkp_study_v2_publishstage.pdf",
    where: "Other",
    when: "unclear",
    author: "IKP",
    language: "EN",
    what: "study_report",
  },
  {
    id: "sr_011",
    title: "ZKP Study Report (Draft)",
    path: "study-reports/zkp/BGIN-ZKPdoc.pdf",
    where: "Other",
    when: "2023/07",
    author: "IKP",
    language: "EN",
    what: "study_report",
  },

  // ===== Governance Doc =====
  {
    id: "gd01",
    title: "Draft Code of Conduct",
    path: "block-events/block1/Draft_Code_of_Conduct.pdf",
    where: "Block 1",
    when: "2020/06",
    author: "Other",
    language: "EN",
    what: "governance_doc",
  },
  {
    id: "gd02",
    title: "Draft Note Well",
    path: "block-events/block1/Draft_Note_Well.pdf",
    where: "Block 1",
    when: "2020/06",
    author: "Other",
    language: "EN",
    what: "governance_doc",
  },
  {
    id: "gd03",
    title: "Draft Roadmap",
    path: "block-events/block1/Draft_Roadmap.pdf",
    where: "Block 1",
    when: "2020/06",
    author: "Other",
    language: "EN",
    what: "governance_doc",
  },
  {
    id: "gd04",
    title: "BGIN Code of Conduct",
    path: "governance/20200611_BGIN_Code_of_Conduct.pdf",
    where: "Other",
    when: "2020/06", // 20200611 in filename
    author: "Other",
    language: "EN",
    what: "governance_doc",
  },
  {
    id: "gd05",
    title: "BGIN Note Well",
    path: "governance/20200611_BGIN_Note_Well.pdf",
    where: "Other",
    when: "2020/06", // 20200611 in filename
    author: "Other",
    language: "EN",
    what: "governance_doc",
  },
  {
    id: "gd06",
    title: "BGIN Group Guidelines & Procedures",
    path: "governance/BGIN_Group_Guidelines_Procedures.pdf",
    where: "Other",
    when: "2024/11",
    author: "Other",
    language: "EN",
    what: "governance_doc",
  },
  {
    id: "gd07",
    title: "BGIN Steering Committee Charter",
    path: "governance/BGIN_Steering_Committee_Charter.pdf",
    where: "Other",
    when: "2024/11",
    author: "Other",
    language: "EN",
    what: "governance_doc",
  },
  {
    id: "gd08",
    title: "BGIN Steering Committee Member Duties",
    path: "governance/BGIN_Steering_Committee_Member_Duties.pdf",
    where: "Other",
    when: "unclear",
    author: "Other",
    language: "EN",
    what: "governance_doc",
  },
  {
    id: "gd09",
    title: "BGIN ByLaw (November 2024)",
    path: "governance/ByLaw_November2024.pdf",
    where: "Other",
    when: "2024/11", // "November2024" in filename
    author: "Other",
    language: "EN",
    what: "governance_doc",
  },
  {
    id: "gd10",
    title: "DRAFT BGIN IPR Policy",
    path: "governance/DRAFT_BGIN_IPR_Policy.pdf",
    where: "Other",
    when: "unclear",
    author: "Other",
    language: "EN",
    what: "governance_doc",
  },
  {
    id: "gd11",
    title: "DRAFT BGIN Process Document",
    path: "governance/DRAFT_BGIN_Process_Document.pdf",
    where: "Other",
    when: "unclear",
    author: "Other",
    language: "EN",
    what: "governance_doc",
  },
  {
    id: "gd12",
    title: "BGIN Cybersecurity Working Group Charter",
    path: "projects/cybersecurity-standards/BGIN Cybersecurity Working Group Charter.pdf",
    where: "Other",
    when: "unclear",
    author: "CS",
    language: "EN",
    what: "governance_doc",
  },
];
