export const programData = {
  program: {
    day1: {
      date: "October 15, 2026",
      sessions: [
        {
          id: "1-1",
          title: "Opening Plenary",
          time: "09:00 - 09:20",
          room: "Room A",
          summary:
            "Welcome and orientation to BGIN Block 15. Overview of the two-day agenda and working group priorities in Washington, D.C.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-1",
          agenda: [],
          documents: [],
          relatedProjects: [],
          relatedProjectSlugs: [],
        },
        {
          id: "1-2",
          title: "Keynote: PQC",
          time: "09:20 - 09:50",
          room: "Room A",
          summary:
            "Keynote on post-quantum cryptography migration and crypto agility for blockchain and digital-asset systems.",
          wg: "IKP",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-2",
          agenda: [],
          documents: [],
          relatedProjects: ["PQC Migration"],
          relatedProjectSlugs: ["pqc-migration"],
        },
        {
          id: "1-3",
          title: "FASE: AI & Blockchain",
          time: "09:50 - 11:20",
          room: "Room A",
          summary:
            "Exploring synergies and risks where AI and blockchain intersect — data, governance, and real-world use cases.",
          wg: "FASE",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-3",
          agenda: [],
          documents: [],
          relatedProjects: ["AI and Blockchain"],
          relatedProjectSlugs: ["ai-blockchain"],
        },
        {
          id: "1-4",
          title: "IKP: PQC Migration",
          time: "09:50 - 11:20",
          room: "Room B",
          summary:
            "IKP working session on crypto agility and post-quantum cryptography migration for blockchain stacks and wallets.",
          wg: "IKP",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-4",
          agenda: [],
          documents: [],
          relatedProjects: ["PQC Migration"],
          relatedProjectSlugs: ["pqc-migration"],
        },
        {
          id: "1-5",
          title: "Agent Hack / Local Pi Private Knowledge Network",
          time: "09:50 - 11:20",
          room: "Open Space",
          summary:
            "Agent Hack alongside Local Pi private knowledge network connectivity — hands-on agentic AI work in open space.",
          wg: "Agentic AI",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-5",
          agenda: [],
          documents: [],
          relatedProjects: ["Agent Standards and Frameworks"],
          relatedProjectSlugs: ["agent-standards"],
        },
        {
          id: "1-6",
          title: "Cyber: Governance of the Security Supply Chain",
          time: "11:30 - 13:00",
          room: "Room A",
          summary:
            "Cybersecurity working session on the Governance of the Security Supply Chain project — vendor guidelines, dependency risk, and supply-chain integrity across blockchain software and operations.",
          wg: "Cyber Security",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-6",
          agenda: [],
          documents: [],
          relatedProjects: ["Governance of the Security Supply Chain"],
          relatedProjectSlugs: ["security-supply-chain"],
        },
        {
          id: "1-7",
          title: "IKP: PQC Migration (2)",
          time: "11:30 - 13:00",
          room: "Room B",
          summary:
            "Continued IKP session on post-quantum cryptography migration and crypto agility.",
          wg: "IKP",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-7",
          agenda: [],
          documents: [],
          relatedProjects: ["PQC Migration"],
          relatedProjectSlugs: ["pqc-migration"],
        },
        {
          id: "1-8",
          title: "Industry Session 1",
          time: "14:00 - 14:45",
          room: "Room A",
          summary:
            "Industry-led session on policy and market themes. Partner organization to be announced.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-8",
          agenda: [],
          documents: [],
          relatedProjects: [
            "Harmonization among Crypto-asset, Stablecoin and Tokenized Deposit",
          ],
          relatedProjectSlugs: ["harmonization"],
        },
        {
          id: "1-9",
          title: "Industry Session 2",
          time: "14:45 - 15:30",
          room: "Room A",
          summary:
            "Second industry-led session. Partner organization and format to be announced.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-9",
          agenda: [],
          documents: [],
          relatedProjects: [
            "Harmonization among Crypto-asset, Stablecoin and Tokenized Deposit",
          ],
          relatedProjectSlugs: ["harmonization"],
        },
        {
          id: "1-10",
          title: "BGIN Business Meeting",
          time: "15:40 - 17:10",
          room: "Room A",
          summary:
            "BGIN steering and business session for members and stakeholders.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-10",
          agenda: [],
          documents: [],
          relatedProjects: [],
          relatedProjectSlugs: [],
        },
        {
          id: "1-11",
          title: "Networking Reception",
          time: "17:10-",
          room: "TBD",
          summary: "Networking reception for all Block 15 participants.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-11",
          agenda: [],
          documents: [],
          relatedProjects: [],
          relatedProjectSlugs: [],
        },
      ],
    },
    day2: {
      date: "October 16, 2026",
      sessions: [
        {
          id: "2-1",
          title: "Day 2 Opening",
          time: "09:00 - 09:20",
          room: "Room A",
          summary: "Day 2 welcome and agenda overview.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-1",
          agenda: [],
          documents: [],
          relatedProjects: [],
          relatedProjectSlugs: [],
        },
        {
          id: "2-2",
          title: "Keynote: Policy",
          time: "09:20 - 09:50",
          room: "Room A",
          summary:
            "Policy keynote framing digital-asset regulation and governance priorities in Washington, D.C.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-2",
          agenda: [],
          documents: [],
          relatedProjects: [
            "Harmonization among Crypto-asset, Stablecoin and Tokenized Deposit",
          ],
          relatedProjectSlugs: ["harmonization"],
        },
        {
          id: "2-3",
          title: "FASE: Industrial Design of Digital Assets",
          time: "09:50 - 11:20",
          room: "Room A",
          summary:
            "Working session on industrial design and shared industry-structure models for digital-asset ecosystems.",
          wg: "FASE",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-3",
          agenda: [],
          documents: [],
          relatedProjects: [
            "Harmonization among Crypto-asset, Stablecoin and Tokenized Deposit",
          ],
          relatedProjectSlugs: ["harmonization"],
        },
        {
          id: "2-4",
          title:
            "Cyber + IKP: Security AI Agent — Information Sharing & Vulnerability Handling",
          time: "09:50 - 11:20",
          room: "Room B",
          summary:
            "Joint Cyber Security and IKP session on the Security AI Agent workstream — information sharing and vulnerability handling in agentic systems.",
          wg: "Cyber Security",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-4",
          agenda: [],
          documents: [],
          relatedProjects: [
            "Security AI Agent",
            "Cybersecurity Information Sharing Framework",
          ],
          relatedProjectSlugs: [
            "security-ai-agent",
            "cybersecurity-information-sharing",
          ],
        },
        {
          id: "2-5",
          title: "FASE: Decentralized Compute & Market Structure",
          time: "11:30 - 13:00",
          room: "Room A",
          summary:
            "Discussion on decentralized compute infrastructure and digital-asset industry market structure.",
          wg: "FASE",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-5",
          agenda: [],
          documents: [],
          relatedProjects: [
            "Technical Metrics for Decentralization",
            "Harmonization among Crypto-asset, Stablecoin and Tokenized Deposit",
          ],
          relatedProjectSlugs: ["decentralization-metrics", "harmonization"],
        },
        {
          id: "2-6",
          title:
            "IKP: Privacy Enhanced Authentication, ZKP & Proof of Personhood",
          time: "11:30 - 13:00",
          room: "Room B",
          summary:
            "IKP session on privacy-enhanced authentication, zero-knowledge proofs, and proof of personhood mechanisms.",
          wg: "IKP",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-6",
          agenda: [],
          documents: [],
          relatedProjects: ["Privacy Enhanced Authentication"],
          relatedProjectSlugs: ["privacy-enhanced-auth"],
        },
        {
          id: "2-7",
          title: "FASE: Stablecoin Policy — a Global Outlook",
          time: "14:00 - 14:45",
          room: "Room A",
          summary:
            "Comparative discussion of stablecoin regulatory approaches and policy priorities across jurisdictions.",
          wg: "FASE",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-7",
          agenda: [],
          documents: [],
          relatedProjects: ["Practical Stablecoin Implementation Guide"],
          relatedProjectSlugs: ["stablecoin-guide"],
        },
        {
          id: "2-8",
          title: "Cyber + IKP: Offline Key Management",
          time: "14:00 - 14:45",
          room: "Room B",
          summary:
            "Joint Cyber Security and IKP session on standards and good practices for offline key management.",
          wg: "Cyber Security",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-8",
          agenda: [],
          documents: [],
          relatedProjects: ["Offline Key Management"],
          relatedProjectSlugs: ["offline-key-management"],
        },
        {
          id: "2-9",
          title:
            "AML Policy, Forensics & Analytics — Common Taxonomy (FASE/IKP)",
          time: "15:40 - 17:10",
          room: "Room A",
          summary:
            "Joint FASE and IKP session on AML policy, forensics and analytics, and a common taxonomy for harmful on-chain activities.",
          wg: "FASE",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-9",
          agenda: [],
          documents: [],
          relatedProjects: [
            "Forensics & Analysis",
            "Illicit Activities (Common Lexicon)",
          ],
          relatedProjectSlugs: ["forensics-analysis", "illicit-activities"],
        },
        {
          id: "2-10",
          title: "Cyber: Security Target & Protection Profile (ST/PP)",
          time: "15:40 - 17:10",
          room: "Room B",
          summary:
            "Cybersecurity session on Security Target and Protection Profile standards for wallet security assurance.",
          wg: "Cyber Security",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-10",
          agenda: [],
          documents: [],
          relatedProjects: [
            "Security Target & Protection Profile (ST/PP)",
          ],
          relatedProjectSlugs: ["st-pp"],
        },
      ],
    },
  },
  rooms: {
    "Room A": {
      displayName: "Georgetown University — Room A",
      capacity: "TBD",
      image: "/images/Events/block13/Arrupe Hall - outside.png",
      address: "3700 O St NW, Washington, DC 20057, United States",
    },
    "Room B": {
      displayName: "Georgetown University — Room B",
      capacity: "TBD",
      image: "/images/Events/block13/Hairiri - outisde.png",
      address: "3700 O St NW, Washington, DC 20057, United States",
    },
    "Open Space": {
      displayName: "Georgetown University — Open Space",
      capacity: "TBD",
      image: null,
      address: "3700 O St NW, Washington, DC 20057, United States",
    },
    TBD: {
      displayName: "To Be Determined",
      capacity: "TBD",
      image: null,
      address: "3700 O St NW, Washington, DC 20057, United States",
    },
  },
  workingGroups: {
    IKP: {
      name: "Identity, Key Management & Privacy",
      abbreviation: "IKP",
      color: "amber",
      chairs: ["Mitchell Travers", "Nat Sakimura"],
      description:
        "Focuses on identity management, key management strategies, and privacy-preserving technologies",
      documentsLink: "https://bgin-global.org/activities/working-groups",
    },
    "Cyber Security": {
      name: "Cybersecurity Working Group",
      abbreviation: "CS",
      color: "red",
      chairs: ["Tomofumi Okubo", "Takaya Sugino"],
      description:
        "Addresses security frameworks, threat intelligence, and cybersecurity standards for blockchain systems",
      documentsLink: "https://bgin-global.org/activities/working-groups",
    },
    CS: {
      name: "Cybersecurity Working Group",
      abbreviation: "CS",
      color: "red",
      chairs: ["Tomofumi Okubo", "Takaya Sugino"],
      description:
        "Addresses security frameworks, threat intelligence, and cybersecurity standards for blockchain systems",
      documentsLink: "https://bgin-global.org/activities/working-groups",
    },
    FASE: {
      name: "Financial Applications & Social Economics",
      abbreviation: "FASE",
      color: "blue",
      chairs: ["Chloe White", "Joseph Beverley"],
      description:
        "Examines financial applications, stablecoins, and socio-economic impacts of blockchain technology",
      documentsLink: "https://bgin-global.org/activities/working-groups",
    },
    "Agentic AI": {
      name: "Agentic AI Working Group",
      abbreviation: "Agentic AI",
      color: "yellow",
      chairs: ["TBD"],
      description:
        "Focuses on AI agent governance and security information sharing platforms",
      documentsLink: "https://bgin-global.org/activities/working-groups",
    },
    General: {
      name: "General Session",
      abbreviation: "General",
      color: "gray",
      chairs: ["Shinichiro Matsuo"],
      description: "Plenary, keynote, and networking sessions",
      documentsLink: null,
    },
  },
};
