export const programData = {
  program: {
    day1: {
      date: "October 15, 2026",
      sessions: [
        {
          id: "1-1",
          title: "Opening Plenary",
          time: "09:00 - 09:20",
          room: "Room A",
          summary:
            "Welcome and orientation to BGIN Block 15. Overview of the two-day agenda and working group priorities in Washington, D.C.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-1",
          agenda: [
            "Welcome to Block 15 in Washington, D.C.",
            "What a Block meeting produces: practitioner standards as deliverables, and the path from BGIN documents to ISO TC 307",
            "The two days at a glance: what each working group room (IKP, Cyber Security, FASE, Agentic AI) is working on and aims to settle this Block",
            "How to take part: how session outcomes become meeting reports, the public-comment cycle, and following the work on the BGIN Discourse",
          ],
          documents: [],
          relatedProjects: [],
          relatedProjectSlugs: [],
        },
        {
          id: "1-2",
          title: "Keynote: Crypto Agility in the Quantum and AI Era",
          time: "09:20 - 09:50",
          room: "Room A",
          summary:
            "Opening keynote by Alex Pruden (CEO & Co-Founder, Project Eleven). Crypto agility as an essential design principle for digital assets and blockchain systems, the practical challenges of migrating systems that secure billions of dollars in value, and why organizations should prepare for cryptographic change well before existing standards are broken.",
          wg: "IKP",
          speakers: "Alex Pruden (CEO & Co-Founder, Project Eleven)",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-2",
          agenda: [
            "Why the decades-long assumption of stable cryptographic infrastructure is breaking down: quantum computing as a migration imperative, AI as an accelerant of threat pace and sophistication",
            "Crypto agility as an essential design principle for digital assets and blockchain systems",
            "The practical challenges of migrating systems that secure billions of dollars in value",
            "Why organizations should begin preparing for cryptographic change well before existing standards are broken",
          ],
          documents: [],
          relatedProjects: ["PQC Migration"],
          relatedProjectSlugs: ["pqc-migration"],
        },
        {
          id: "1-3",
          title: "FASE: AI & Blockchain",
          time: "09:50 - 11:20",
          room: "Room A",
          summary:
            "AI and blockchain systems are beginning to depend on each other in practice rather than in theory: AI agents hold wallets, pay for services in stablecoins and act on-chain for users; blockchains record the provenance of data, models and outputs and settle the compute AI workloads consume; and AI is applied to on-chain analytics, smart-contract auditing and security monitoring. This session gives an overview of the industry as it stands today, then turns to the open questions that matter most for policymakers and practitioners. The discussion will inform the scope of FASE's AI + Blockchain workstream and identify topics for future written contributions.",
          wg: "FASE",
          speakers: "Joseph Beverley (Co-Chair, FASE)",
          moderator: "Joseph Beverley (Co-Chair, FASE)",
          detailPage: "/events/20261015-block15/sessions/1-3",
          agenda: [
            "Overview of the AI and blockchain industry today: the major developments of the past year, how each technology is adapting to accommodate the other, and where the gaps remain",
            "AI agents that hold wallets, pay for services in stablecoins, and act on-chain on behalf of users",
            "Blockchains for the provenance of data, models and outputs, and for coordinating and settling AI compute; AI applied to on-chain analytics, smart-contract auditing and security monitoring",
            "Open question: who is accountable when an autonomous agent transacts?",
            "Open question: how should agent identity and authorisation be established?",
            "Open question: how do existing AML/CFT and consumer-protection rules apply to machine-initiated activity?",
            "Open question: where does the convergence create opportunities that current regulatory frameworks do not yet recognise?",
            "Scope of the FASE AI + Blockchain workstream and topics for future written contributions",
          ],
          documents: [],
          relatedProjects: ["AI and Blockchain"],
          relatedProjectSlugs: ["ai-blockchain"],
        },
        {
          id: "1-4",
          title: "IKP: PQC Migration",
          time: "09:50 - 11:20",
          room: "Room B",
          summary:
            "First of two IKP working sessions on the PQC Migration Prize Competition (hosted by METI/NEDO; BGIN coordinates and runs the neutral evaluation testbed). Picks up from the opening keynote on crypto agility and walks through the public competition repository — core outcomes, the draft evaluation metrics register, the testbed scheme register and bench harness — then puts the open evaluation questions to the room.",
          wg: "IKP",
          speakers: "Kanta Matsuura, Tadahiko Itoh",
          moderator: "Mitchell Travers (Co-Chair, IKP)",
          detailPage: "/events/20261015-block15/sessions/1-4",
          agenda: [
            "From the keynote to the competition: crypto agility as the thing being evaluated — deployment, evaluation, testbeds, and migration governance on live public chains, not new primitives",
            "Tour of the public competition repository: governance, core outcomes O1–O6, the 22-metric evaluation register (draft v0), testbed scheme register and harness specification",
            "Resource estimates and the ECDSA.fail community: what the benchmark numbers mean for migration timelines and for judging criteria",
            "Open question: is the headline quantity total overhead or migration speed?",
            "Open question: who must upgrade first — node operators or users — and how the metrics reflect that burden split",
            "Open question: scoring the legitimate-owner-versus-attacker race during a migration window",
            "Tagging each metric by the attack class it defends against — on-spend, at-rest, on-setup (the GDC26 taxonomy)",
          ],
          documents: [
            {
              title: "PQC Migration Prize — competition repository (public record)",
              link: "https://github.com/bgin-global/pqc-agility-competition",
              type: "Repository",
            },
            {
              title: "Workshop roadmap W1–W6 (Block 15 = W2)",
              link: "https://github.com/bgin-global/pqc-agility-competition/blob/main/workshops/ROADMAP.md",
              type: "Roadmap",
            },
            {
              title: "Evaluation metrics register (draft v0) and open questions",
              link: "https://github.com/bgin-global/pqc-agility-competition/blob/main/evaluation/METRICS.md",
              type: "Draft",
            },
            {
              title: "Core outcomes O1–O6 (draft v0)",
              link: "https://github.com/bgin-global/pqc-agility-competition/blob/main/OUTCOMES.md",
              type: "Draft",
            },
            {
              title: "Testbed scheme register",
              link: "https://github.com/bgin-global/pqc-agility-competition/blob/main/testbed/SCHEMES.md",
              type: "Specification",
            },
            {
              title: "GDC26 PQC migration meeting report (3 Sep 2026)",
              link: "/news/260903-gdc26-pqc-migration",
              type: "Meeting report",
            },
            {
              title: "Competition discussion on the BGIN Discourse",
              link: "https://bgin.discourse.group/c/post-quantum-crypto-agility-competition/44",
              type: "Discussion",
            },
          ],
          relatedProjects: ["PQC Migration"],
          relatedProjectSlugs: ["pqc-migration"],
        },
        {
          id: "1-5",
          title: "Agent Hack / Local Pi Private Knowledge Network",
          time: "09:50 - 11:20",
          room: "Open Space",
          summary:
            "Agent Hack alongside Local Pi private knowledge network connectivity — hands-on agentic AI work in open space.",
          wg: "Agentic AI",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-5",
          agenda: [
            "Open-space, hands-on build session running alongside the morning working group sessions — drop in at any point",
            "Local Pi private knowledge network: small local nodes that hold a person's or a group's knowledge privately and share selectively between peers",
            "Agent Hack: building and testing agents against that network — what an agent may read, what it may share, and on whose authority",
            "Link to the Security AI Agent and agent standards work: which patterns from the hack are worth writing down",
            "Show-and-tell of what was built before the break",
          ],
          documents: [],
          relatedProjects: ["Agent Standards and Frameworks"],
          relatedProjectSlugs: ["agent-standards"],
        },
        {
          id: "1-6",
          title: "Cyber: Governance of the Security Supply Chain",
          time: "11:30 - 13:00",
          room: "Room A",
          summary:
            "Cybersecurity risks in crypto-asset services increasingly arise not only from vulnerabilities in blockchain protocols or the compromise of signing keys, but also from dependencies across the broader operational and technology supply chain. Recent incidents have highlighted risks involving external service providers, cloud and CI/CD environments, transaction-generation processes, administrative privileges, smart contracts, oracles, bridges, and other external components.\n\n" +
            "This session will use the June 2026 research paper Cybersecurity Issues and Countermeasures in Crypto-Asset-Related Businesses as a starting point for discussion. The paper maps the structure and dependencies of the crypto-asset ecosystem, examines recent cybersecurity incidents, and identifies priority areas including third-party risk management, protection against code and transaction tampering, controls over smart contracts and DeFi operations, and the effective use of third-party assessments.\n\n" +
            "Building on these findings, participants will discuss how security-supply-chain risks should be governed in practice: how critical dependencies should be identified, what operators should verify themselves rather than delegate to vendors or auditors, how responsibilities should be allocated across service providers and subcontractors, and what contractual, technical, monitoring, and assurance mechanisms are appropriate.\n\n" +
            "The discussion will provide input to BGIN’s ongoing Governance of the Security Supply Chain project, with the aim of developing practical principles and vendor-guideline considerations for crypto and blockchain systems.",
          wg: "Cyber Security",
          speakers: "",
          moderator: "Julien Bringer (Chair, Cyber Security)",
          detailPage: "/events/20261015-block15/sessions/1-6",
          agenda: [
            "Key findings from the June 2026 research paper, including recent incidents, ecosystem dependencies, and priority areas for cybersecurity risk management.",
            "Discussion on how operators should identify and manage risks arising from vendors, subcontractors, software components, cloud services, smart contracts, oracles, bridges, and other external dependencies.",
            "Discussion on what operators should verify themselves, what may be delegated to third parties, and how audits, monitoring, contractual controls, and technical safeguards should be combined.",
            "Identify common principles and practical considerations that could inform BGIN’s work on security supply-chain governance and vendor guidelines.",
          ],
          documents: [
            {
              title:
                "Cybersecurity Issues and Countermeasures in Crypto-Asset-Related Businesses — Research paper, June 30, 2026 (Deloitte Tohmatsu LLC)",
              link: "/documents/block-events/block15/CS/ResearchPaper_dtc_20260630_en.pdf",
              type: "PDF",
            },
          ],
          relatedProjects: ["Governance of the Security Supply Chain"],
          relatedProjectSlugs: ["security-supply-chain"],
        },
        {
          id: "1-7",
          title: "IKP: PQC Migration (2)",
          time: "11:30 - 13:00",
          room: "Room B",
          summary:
            "Second IKP working session on the PQC Migration Prize Competition — the decisions session. Crypto agility as a governance property and the NIST PQC signature migration path across Bitcoin, Ethereum, and other ecosystems, with NIST participation. Block 15 is the second workshop (W2) of the six-month series: the aim is to seat the evaluation committee, take the scheme scope rulings, and move the metrics register from v0 to v1 on the pathway from competition to BGIN Standard to ISO/TC 307.",
          wg: "IKP",
          speakers: "Kanta Matsuura,Tadahiko Itoh",
          moderator: "Mitchell Travers (Co-Chair, IKP)",
          detailPage: "/events/20261015-block15/sessions/1-7",
          agenda: [
            "Seating the evaluation committee (Phase A): nominations, conflict-of-interest disclosures, chairs",
            "Scheme scope rulings for the testbed: ML-DSA, SLH-DSA, FN-DSA, XMSS, LMS, and the classical baselines — recorded as decision records",
            "Metrics register v0 → v1: consolidating the feedback from session 1-4",
            "Reference CPU class and reference transaction mix / block — anchors for the performance metrics",
            "Whether consensus-layer and user-level evidence are scored on one rubric or two",
            "Proposed open-benchmark model for calibration tracks (decision record 0001): open, reproducible calibration versus measured and attested prize evaluation",
            "Pathway and next steps: testbed workshop (Nov), rubric, “PQC-ready chain” definition and call-text input package at the SSR co-located PQC workshop (13 Dec, Baltimore), BGIN Standard outline (Feb 2027) toward ISO/TC 307",
          ],
          documents: [
            {
              title: "PQC Migration Prize — competition repository (public record)",
              link: "https://github.com/bgin-global/pqc-agility-competition",
              type: "Repository",
            },
            {
              title: "Workshop roadmap W1–W6 (Block 15 = W2)",
              link: "https://github.com/bgin-global/pqc-agility-competition/blob/main/workshops/ROADMAP.md",
              type: "Roadmap",
            },
            {
              title: "Evaluation metrics register (draft v0) and open questions",
              link: "https://github.com/bgin-global/pqc-agility-competition/blob/main/evaluation/METRICS.md",
              type: "Draft",
            },
            {
              title: "Governance and evaluation committee (phases, composition, decision process)",
              link: "https://github.com/bgin-global/pqc-agility-competition/blob/main/GOVERNANCE.md",
              type: "Governance",
            },
            {
              title: "Conflict-of-interest policy (draft)",
              link: "https://github.com/bgin-global/pqc-agility-competition/blob/main/evaluation/COI_POLICY.md",
              type: "Policy",
            },
            {
              title: "Decision record 0001 — open-benchmark model (proposed)",
              link: "https://github.com/bgin-global/pqc-agility-competition/blob/main/decisions/0001-open-benchmark-model.md",
              type: "Decision record",
            },
            {
              title: "Competition discussion on the BGIN Discourse",
              link: "https://bgin.discourse.group/c/post-quantum-crypto-agility-competition/44",
              type: "Discussion",
            },
          ],
          relatedProjects: ["PQC Migration"],
          relatedProjectSlugs: ["pqc-migration"],
        },
        {
          id: "1-8",
          title: "Industry Session 1",
          time: "14:00 - 14:45",
          room: "Room A",
          summary:
            "Industry-led session on policy and market themes. Partner organization to be announced.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-8",
          agenda: [
            "Industry presentation (partner to be announced)",
            "Discussion: what industry needs from harmonized treatment of crypto-assets, stablecoins and tokenized deposits",
            "Inputs to the FASE harmonization discussion paper and industry-structure work",
          ],
          documents: [],
          relatedProjects: [
            "Harmonization among Crypto-asset, Stablecoin and Tokenized Deposit",
          ],
          relatedProjectSlugs: ["harmonization"],
        },
        {
          id: "1-9",
          title: "Industry Session 2",
          time: "14:45 - 15:30",
          room: "Room A",
          summary:
            "Second industry-led session. Partner organization and format to be announced.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-9",
          agenda: [
            "Industry presentation (partner and format to be announced)",
            "Practitioner perspectives on where standards would reduce cost or risk",
            "Inputs to the FASE harmonization deliverables",
          ],
          documents: [],
          relatedProjects: [
            "Harmonization among Crypto-asset, Stablecoin and Tokenized Deposit",
          ],
          relatedProjectSlugs: ["harmonization"],
        },
        {
          id: "1-10",
          title: "BGIN Business Meeting",
          time: "15:40 - 17:10",
          room: "Room A",
          summary:
            "BGIN steering and business session for members and stakeholders.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-10",
          agenda: [
            "Day 1 reports from each working group room",
            "Documents in progress: drafts, public-comment iterations, and publications expected after Block 15",
            "Standards pathway: the ISO TC 307 liaison and which documents are ready to go forward",
            "Membership, sponsorship and contributor participation",
            "Upcoming meetings: workshops between Blocks and the next Block",
          ],
          documents: [],
          relatedProjects: [],
          relatedProjectSlugs: [],
        },
        {
          id: "1-11",
          title: "Networking Reception",
          time: "17:10-",
          room: "TBD",
          summary: "Networking reception for all Block 15 participants.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/1-11",
          agenda: [],
          documents: [],
          relatedProjects: [],
          relatedProjectSlugs: [],
        },
      ],
    },
    day2: {
      date: "October 16, 2026",
      sessions: [
        {
          id: "2-1",
          title: "Day 2 Opening",
          time: "09:00 - 09:20",
          room: "Room A",
          summary: "Day 2 welcome and agenda overview.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-1",
          agenda: [
            "Day 1 recap: what each room settled and what it left open",
            "Day 2 programme and how the rooms connect",
            "Logistics and closing arrangements",
          ],
          documents: [],
          relatedProjects: [],
          relatedProjectSlugs: [],
        },
        {
          id: "2-2",
          title: "Keynote: Policy",
          time: "09:20 - 09:50",
          room: "Room A",
          summary:
            "Policy keynote framing digital-asset regulation and governance priorities in Washington, D.C.",
          wg: "General",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-2",
          agenda: [
            "The policy landscape for digital assets in the United States and internationally",
            "Stablecoins, tokenized deposits and market structure: where regulation is heading",
            "How industry-developed standards inform regulation and supervision",
            "Framing for the Day 2 FASE and cross-working-group sessions",
          ],
          documents: [],
          relatedProjects: [
            "Harmonization among Crypto-asset, Stablecoin and Tokenized Deposit",
          ],
          relatedProjectSlugs: ["harmonization"],
        },
        {
          id: "2-3",
          title: "FASE: Industrial Structure of Digital Assets",
          time: "09:50 - 11:20",
          room: "Room A",
          summary:
            "Japan is moving crypto-asset regulation from the Payment Services Act to the Financial Instruments and Exchange Act, and the detailed rules are now being written. The Discussion Paper \"The Industrial Structure of Digital Assets\", prepared by the Study Group on the Ideal Industrial Structure for Digital Assets and first presented at Block 14 in Tokyo, starts from a simple observation: rules designed without a shared picture of how the industry is actually structured risk not working as intended. This session maps the stakeholders and structural features of the digital-asset industry, closes with six open questions, and invites participants to propose ways to address or mitigate them.",
          wg: "FASE",
          speakers: "Joseph Beverley (Co-Chair, FASE), Ken Katayama (Senior Chief Researcher, Nomura Research Institute, Ltd.), Ken Kawai (Partner, Anderson Mōri & Tomotsune, Gaikokuho Kyodo Jigyo), Tetsuro Morishita (Professor, Faculty of Law, Sophia University)",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-3",
          agenda: [
            "Mapping the stakeholders and structural features of the digital-asset industry: a thin domestic intermediary layer that depends on a technology, audit and market-making layer largely provided overseas; a competitive imbalance between registered operators and offshore or decentralised services; and an industry that is vertically integrated and largely loss-making",
            "Competitive asymmetry: how can Japan protect users and support local operators when offshore exchanges and DeFi services can reach Japanese users without bearing the same regulatory costs?",
            "Infrastructure and global markets: which parts of the crypto infrastructure stack should Japan develop and be competitive in, and which can it rely on global providers for?",
            "Compete vs. share: which functions should each digital asset venture run itself, and which could be provided by third parties or shared across the industry?",
            "Public chains and their public-good nature: how should Japan contribute to the core technology and developer ecosystems of public blockchains, rather than benefit from work maintained elsewhere?",
            "Coexistence with DeFi: is today's approach — regulating centralised exchanges but having no clear regulatory touchpoint for decentralised exchanges — sustainable, and where should the regulatory line be drawn?",
            "Diversifying capital markets: how could token-based fundraising become accessible to people using their own wallets while protecting investors, especially as the boundary between crypto tokens and securities blurs?",
            "Open discussion: participants propose ways to address or mitigate the six questions",
          ],
          documents: [
            {
              title: "Discussion Paper: The Industrial Structure of Digital Assets (Study Group on the Ideal Industrial Structure for Digital Assets, version of 11 June 2026)",
              link: "https://docs.google.com/document/d/1JEJYKLRpNIGZe36kCbjQbzbGc7PGF02U/edit",
              type: "Discussion Paper",
            },
            {
              title: "FASE contribution: Offshore, Infrastructure, Public Goods — early findings on three open questions (discussion draft, 23 Sep 2026)",
              link: "https://docs.google.com/presentation/d/1C7DsLsA9UCPvYBO8r6eXIehZN3-fa7aJUiiCU6yczXc/edit",
              type: "Slides",
            },
          ],
          relatedProjects: [
            "Harmonization among Crypto-asset, Stablecoin and Tokenized Deposit",
          ],
          relatedProjectSlugs: ["harmonization"],
        },
        {
          id: "2-4",
          title:
            "Cyber + IKP: Security AI Agent — Information Sharing & Vulnerability Handling",
          time: "09:50 - 11:20",
          room: "Room B",
          summary:
            "Joint Cyber Security and IKP session on the Security AI Agent workstream — information sharing and vulnerability handling in agentic systems.",
          wg: "Cyber Security",
          speakers: "",
          moderator: "Julien Bringer (Chair, Cyber Security)",
          detailPage: "/events/20261015-block15/sessions/2-4",
          agenda: [
            "Picking up from the GDC26 Geneva breakout on vulnerability handling in the agentic AI era",
            "When AI speeds up exploit development: what that does to disclosure timelines and coordinated response",
            "Security AI Agent workflows mapped to the published Cybersecurity Information Sharing Framework",
            "The IKP angle: what an agent may share, with whom, and under what delegated authority — identity, keys and access control for agents that exchange security information",
            "Path to a first public draft: scope, owners and timeline",
          ],
          documents: [],
          relatedProjects: [
            "Security AI Agent",
            "Cybersecurity Information Sharing Framework",
          ],
          relatedProjectSlugs: [
            "security-ai-agent",
            "cybersecurity-information-sharing",
          ],
        },
        {
          id: "2-5",
          title: "FASE: Decentralized Compute & Market Structure",
          time: "11:30 - 13:00",
          room: "Room A",
          summary:
            "Between 2022 and 2026, blockchain-based networks that buy and sell compute (GPU time, inference, model training, rendering) moved from concept to revenue, with named enterprise and AI-laboratory customers, and operators of AI infrastructure increasingly describe compute itself as a commodity. This session asks whether decentralised compute networks can be considered commodity markets, and what would follow if they were, starting from the FASE study report \"Compute-as-Commodity: Observable Flows in Decentralised AI Infrastructure\". It connects to the concentration-of-computing-resources challenge raised in the Industrial Structure session earlier the same morning.",
          wg: "FASE",
          speakers: "Joseph Beverley (Co-Chair, FASE), James Angel (Professor, Georgetown University)",
          moderator: "Joseph Beverley (Co-Chair, FASE)",
          detailPage: "/events/20261015-block15/sessions/2-5",
          agenda: [
            "The study report: six criteria drawn from commodity-market thinking — fungibility, price discovery, settlement and clearing, storage or its substitutes, differentiated counterparty roles, and regulatory recognition — applied to four networks: Akash, Bittensor, Render and Aethir",
            "Does the blockchain layer do real work or is it decorative? Separating productive flows, where tokens meet real external demand, from circular flows that recycle tokens internally",
            "The business models behind these networks, and where they meet or miss the criteria",
            "Gaps in current regulatory and policy treatment, and opportunities for standard-setting",
            "Review of a draft policymaker checklist: could a given network fall within commodity-market regulation or similar regimes?",
            "Link to the concentration-of-computing-resources challenge raised in the Industrial Structure session (2-3)",
          ],
          documents: [
            {
              title: "BGIN SR (FASE): Compute-as-Commodity — Observable Flows in Decentralised Compute Infrastructure (open for comment)",
              link: "https://docs.google.com/document/d/1td0hDHE-Ahq9KG7I-pS0QULtQtvqCy1mmG1pkqdUfks/edit",
              type: "Study Report",
            },
          ],
          relatedProjects: [
            "Technical Metrics for Decentralization",
            "Harmonization among Crypto-asset, Stablecoin and Tokenized Deposit",
          ],
          relatedProjectSlugs: ["decentralization-metrics", "harmonization"],
        },
        {
          id: "2-6",
          title:
            "IKP: Privacy Enhanced Authentication, ZKP & Proof of Personhood",
          time: "11:30 - 13:00",
          room: "Room B",
          summary:
            "IKP session on authentication that proves the claim without disclosing the person. Builds on the two Block 14 meeting reports and the IKP open meetings since: a high-level view of privacy-enhanced authentication, the proof-of-personhood taxonomy and the distinctions it has to keep (with World as a main discussant), how verifiable trust agents acting for a person could carry that assurance, and where zero-knowledge proofs do the work. Twenty minutes for contributors, then open discussion feeding the IKP proof-of-personhood paper.",
          wg: "IKP",
          speakers: "",
          moderator: "Mitchell Travers (Co-Chair, IKP)",
          detailPage: "/events/20261015-block15/sessions/2-6",
          agenda: [
            "Why now: agentic AI raises the cost of not knowing a counterparty is human — picking up from the Block 14 reports (Privacy Enhanced Authentication and Key Management; Proof of Personhood) and the IKP open meetings since",
            "Privacy-enhanced authentication at a high level: prove the claim, not the identity — minimal disclosure, unlinkability, and what each proof actually proves, where the biometric lives, and what revocation means for a credential bound to something that cannot be rotated",
            "Proof-of-personhood taxonomy, with World as a main discussant: the distinctions it has to keep — proof of a unique human versus proof of a specific human, humanity versus uniqueness, linkability scope, how assurance strength is stated rather than asserted, continuity, and agent authority",
            "Verifiable trust agents: an agent acting for a person carrying personhood assurance with delegated scope — does the principal need to be identified, or only assured as human? Personhood credentials as the node, relationship credentials as the edges",
            "Zero-knowledge proofs where they earn their place: predicates that carry assurance strength without revealing the issuer, client-side proving on the phones people already own, and post-quantum readiness of the credential stack",
            "Contributions (20 min): short presentations from contributors to the session",
            "Discussion: gaps nobody owns yet — coercion and credential rental, a threat model per assurance category, governance and appeal when a human is falsely denied",
            "Next steps: room comments into the IKP proof-of-personhood paper, a release for public comment, and the ISO TC 307 Technical Report path",
          ],
          documents: [
            {
              title: "Block 14 MR: Privacy Enhanced Authentication and Key Management",
              link: "/documents/block-events/block14/IKP/IKP_Privacy_Enhanced_Authentication_Key_Management.pdf",
              type: "Meeting Report",
            },
            {
              title: "Block 14 MR: Proof of Personhood",
              link: "/documents/block-events/block14/IKP/IKP_Proof_of_Personhood.pdf",
              type: "Meeting Report",
            },
          ],
          relatedProjects: ["Privacy Enhanced Authentication"],
          relatedProjectSlugs: ["privacy-enhanced-auth"],
        },
        {
          id: "2-L",
          title: "Industry Session (Lunch): World — Proof of Personhood in Practice",
          time: "13:00 - 14:00",
          room: "Room B",
          summary:
            "Lunchtime industry session with World on proof of personhood in practice: proving that someone is a unique human without revealing who they are, and the client-side zero-knowledge tooling behind it. Follows directly from the IKP session on privacy-enhanced authentication, ZKP and proof of personhood (2-6), where World is a main discussant.",
          wg: "General",
          speakers: "World",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-L",
          agenda: [
            "Proof of a unique human, not of a specific human: World's approach to personhood and uniqueness",
            "Privacy architecture: where the biometric data lives, how uniqueness is checked without a lookup of identity, and what stays on the person's device",
            "Client-side zero-knowledge proving on the phones people already own, and verification on chain or in a browser",
            "Use cases in deployment: age verification without a date of birth, and human verification on social platforms",
            "Questions from the room, carried into the IKP proof-of-personhood taxonomy work",
          ],
          documents: [],
          relatedProjects: ["Privacy Enhanced Authentication"],
          relatedProjectSlugs: ["privacy-enhanced-auth"],
        },
        {
          id: "2-7",
          title: "FASE: Stablecoin Policy — a Global Outlook",
          time: "14:00 - 14:45",
          room: "Room A",
          summary:
            "Comparative discussion of stablecoin regulatory approaches and policy priorities across jurisdictions.",
          wg: "FASE",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-7",
          agenda: [
            "Stablecoin regulation compared across jurisdictions: issuer licensing, reserve and redemption requirements, and supervision",
            "Policy priorities and gaps: where approaches diverge and what that costs cross-border use",
            "Implementation realities from issuers and intermediaries",
            "Roadmap update for the Practical Stablecoin Implementation Guide",
          ],
          documents: [],
          relatedProjects: ["Practical Stablecoin Implementation Guide"],
          relatedProjectSlugs: ["stablecoin-guide"],
        },
        {
          id: "2-8",
          title: "Cyber + IKP: Offline Key Management",
          time: "14:00 - 14:45",
          room: "Room B",
          summary:
            "Joint Cyber Security and IKP session on standards and good practices for offline key management.",
          wg: "Cyber Security",
          speakers: "",
          moderator: "Julien Bringer (Chair, Cyber Security)",
          detailPage: "/events/20261015-block15/sessions/2-8",
          agenda: [
            "Picking up from the Block 14 report on Privacy Enhanced Authentication and Key Management: one system holds the keys, another composes the transactions",
            "Good practice for offline keys: generation, air-gapped signing, backup, recovery, and key ceremonies",
            "Tiered key models: separating custody, signing authority and governance power",
            "Post-quantum exposure of cold storage: keys at rest, dormant funds, and planning migration for keys that rarely move",
            "Alignment with the wallet security assurance (ST/PP) work, and owners for the guidance draft",
          ],
          documents: [
            {
              title: "Block 14 MR: Privacy Enhanced Authentication and Key Management",
              link: "/documents/block-events/block14/IKP/IKP_Privacy_Enhanced_Authentication_Key_Management.pdf",
              type: "Meeting Report",
            },
          ],
          relatedProjects: ["Offline Key Management"],
          relatedProjectSlugs: ["offline-key-management"],
        },
        {
          id: "2-9",
          title:
            "AML Policy, Forensics & Analytics — Common Taxonomy (FASE/IKP)",
          time: "15:40 - 17:10",
          room: "Room A",
          summary:
            "Joint FASE and IKP session on AML policy, forensics and analytics, and a common taxonomy for harmful on-chain activities.",
          wg: "FASE",
          speakers: "",
          moderator: "",
          detailPage: "/events/20261015-block15/sessions/2-9",
          agenda: [
            "The Forensics & Analysis document in public comment: review of comments received",
            "Forensics versus analytics: settling the common framing",
            "The illicit-activity common lexicon: terms in progress and how practitioners and policymakers use them",
            "Guidance for VASPs, investigators and educators",
            "Privacy and proportionality in analytics: what can be inferred, by whom, and with what safeguards",
            "Next steps toward publication",
          ],
          documents: [
            {
              title: "Block 14 MR: Forensics & Analysis — Common Lexicon of Harmful Activities",
              link: "/documents/block-events/block14/IKP/IKP_FASE_Forensics_Analysis_Common_Lexicon_Harmful_Activities.pdf",
              type: "Meeting Report",
            },
          ],
          relatedProjects: [
            "Forensics & Analysis",
            "Illicit Activities (Common Lexicon)",
          ],
          relatedProjectSlugs: ["forensics-analysis", "illicit-activities"],
        },
        {
          id: "2-10",
          title: "Cyber: Security Target & Protection Profile (ST/PP)",
          time: "15:40 - 17:10",
          room: "Room B",
          summary:
            "Cybersecurity session on Security Target and Protection Profile standards for wallet security assurance.",
          wg: "Cyber Security",
          speakers: "",
          moderator: "Julien Bringer (Chair, Cyber Security)",
          detailPage: "/events/20261015-block15/sessions/2-10",
          agenda: [
            "Picking up from the GDC26 Geneva breakout on wallet security assurance",
            "Security Target and Protection Profile drafts for wallets: open items",
            "Certification adjacency: how the drafts relate to existing assurance and certification schemes",
            "Alignment with the offline key management guidance",
            "Owners and timeline for follow-on drafting after the Block",
          ],
          documents: [],
          relatedProjects: [
            "Security Target & Protection Profile (ST/PP)",
          ],
          relatedProjectSlugs: ["st-pp"],
        },
      ],
    },
  },
  rooms: {
    "Room A": {
      displayName: "Capitol Campus — Room A (2416)",
      capacity: "TBD",
      image: "/images/Events/block15/room-2416.jpg",
      address: "111 Massachusetts Avenue NW, Washington, DC 20001, United States",
    },
    "Room B": {
      displayName: "Capitol Campus — Room B (2424)",
      capacity: "TBD",
      image: "/images/Events/block15/room-2424.jpg",
      address: "111 Massachusetts Avenue NW, Washington, DC 20001, United States",
    },
    "Open Space": {
      displayName: "Capitol Campus — Open Space",
      capacity: "TBD",
      image: "/images/Events/block15/capitol-campus-lounge.jpg",
      address: "111 Massachusetts Avenue NW, Washington, DC 20001, United States",
    },
    TBD: {
      displayName: "To Be Determined",
      capacity: "TBD",
      image: null,
      address: "111 Massachusetts Avenue NW, Washington, DC 20001, United States",
    },
  },
  workingGroups: {
    IKP: {
      name: "Identity, Key Management & Privacy",
      abbreviation: "IKP",
      color: "amber",
      chairs: ["Mitchell Travers", "Nat Sakimura"],
      description:
        "Focuses on identity management, key management strategies, and privacy-preserving technologies",
      documentsLink: "https://bgin-global.org/activities/working-groups",
    },
    "Cyber Security": {
      name: "Cybersecurity Working Group",
      abbreviation: "CS",
      color: "red",
      chairs: ["Tomofumi Okubo", "Takaya Sugino"],
      description:
        "Addresses security frameworks, threat intelligence, and cybersecurity standards for blockchain systems",
      documentsLink: "https://bgin-global.org/activities/working-groups",
    },
    CS: {
      name: "Cybersecurity Working Group",
      abbreviation: "CS",
      color: "red",
      chairs: ["Tomofumi Okubo", "Takaya Sugino"],
      description:
        "Addresses security frameworks, threat intelligence, and cybersecurity standards for blockchain systems",
      documentsLink: "https://bgin-global.org/activities/working-groups",
    },
    FASE: {
      name: "Financial Applications & Social Economics",
      abbreviation: "FASE",
      color: "blue",
      chairs: ["Chloe White", "Joseph Beverley"],
      description:
        "Examines financial applications, stablecoins, and socio-economic impacts of blockchain technology",
      documentsLink: "https://bgin-global.org/activities/working-groups",
    },
    "Agentic AI": {
      name: "Agentic AI Working Group",
      abbreviation: "Agentic AI",
      color: "yellow",
      chairs: ["TBD"],
      description:
        "Focuses on AI agent governance and security information sharing platforms",
      documentsLink: "https://bgin-global.org/activities/working-groups",
    },
    General: {
      name: "General Session",
      abbreviation: "General",
      color: "gray",
      chairs: ["Shinichiro Matsuo"],
      description: "Plenary, keynote, and networking sessions",
      documentsLink: null,
    },
  },
};
